/*
Christian  Marcol	
CSC 355 Section 402
Assignment 4
October 14, 2019
*/

-- PROBLEM 1
-- USING INNER JOIN
SELECT PATIENT.FIRSTNAME, PATIENT.LASTNAME, PATIENT.INSURANCE
FROM PATIENT 
	INNER JOIN DOCTOR
	ON DOCTORID = DOCTOR.ID
	WHERE DOCTOR.MEDICALGROUP = '281';
-- USING SUBQUERY


-- PROBLEM 2
-- USING SIMPLE WHERE CLAUSE
SELECT COUNT(PROCEDURE.CODE) AS "Pocedure", AVG(PROCEDURE.COST) AS "Cost"
FROM PROCEDURE 
WHERE PROCEDURE.COST < 1000;
--USING SUBQUERY


-- PROBLEM 3
-- USING INNER JOIN
SELECT PATIENT.INSURANCE, COUNT(VISIT.ADMISSIONDATE) AS "Number of Visits"
FROM VISIT
	INNER JOIN PATIENT
	ON VISIT.PID = PATIENT.ID
GROUP BY PATIENT.INSURANCE;


-- PROBLEM 4
-- USING INNER JOINS
SELECT SUM(PROCEDURE.COST) AS "Vivian Wu Procedure Costs"
FROM PROCEDURE
	INNER JOIN SCHEDULE
	ON CODE = PCODE
		INNER JOIN PATIENT
		ON PID = ID
		WHERE PATIENT.FIRSTNAME = 'Vivian' AND PATIENT.LASTNAME = 'Wu'; 


-- PROBLEM 5
-- USING NESTED QUERY
SELECT DOCTOR.ID, DOCTOR.NAME, AVG(PATIENT.AGE)
FROM DOCTOR
	INNER JOIN PATIENT
	ON PATIENT.DOCTORID = DOCTOR.ID
	WHERE EXISTS(SELECT PATIENT.AGE 
					FROM PATIENT
					WHERE PATIENT.INSURANCE = 'HMO Illinois')
GROUP BY DOCTOR.ID, DOCTOR.NAME;


-- PROBLEM 6
-- USING NESTED QUERY
SELECT PATIENT.ID, PATIENT.FIRSTNAME, PATIENT.LASTNAME
FROM PATIENT
WHERE PATIENT.ID IN (SELECT VISIT.PID
                        FROM VISIT
                        WHERE VISIT.ADMISSIONDATE <= '30-SEP-19');
						

-- PROBLEM 7


-- PROBLEM 8
-- USING LEFT JOIN
SELECT PROCEDURE.DESCRIPTION, PROCEDURE.COST * COUNT(SCHEDULE.PCODE) AS "Total Procedure Revenue"
FROM PROCEDURE
	LEFT JOIN SCHEDULE
	ON PROCEDURE.CODE = SCHEDULE.PCODE
GROUP BY PROCEDURE.DESCRIPTION, PROCEDURE.COST
ORDER BY PROCEDURE.COST * COUNT(SCHEDULE.PCODE);

SELECT PATIENT.FIRSTNAME, PATIENT.LASTNAME, PATIENT.ID
FROM PATIENT 
WHERE PATIENT.ID IN (SELECT SCHEDULE.PID
                    FROM SCHEDULE
                    WHERE SCHEDULE.PROCEDUREDATE = '12-OCT-19');





